import type { RecommendationQaPack } from "@/lib/public-api";

export const SAMPLE_RECOMMENDATION_QA_PACK: RecommendationQaPack = {
  packName: "Sample home QA pack",
  description:
    "Safe mock QA pack for repeatable home ranking audits with sample recommendation data.",
  scenarioType: "home",
  query: null,
  productId: null,
  limit: 5,
  baselineSnapshot: {
    scenarioType: "home",
    placement: "home",
    productId: null,
    query: null,
    limit: 5,
    generatedAt: "2026-06-06T13:00:00.000Z",
    comparedAlgorithms: ["rule_based_v1", "rule_based_v2"],
    items: [
      {
        product: {
          id: "prod-1",
          name: "Stable Product",
          seoSlug: null,
          categoryName: "Jackets",
          brand: "North Berry",
          color: "Black",
          price: "1499",
          inStock: true,
          imageUrl: "https://example.com/image.jpg",
          shopName: "Ready Shop",
          shopSlug: "ready-shop",
        },
        rankMovement: null,
        ruleBasedV1: null,
        ruleBasedV2: {
          algorithm: "rule_based_v2",
          rank: 1,
          finalScore: 10,
          reasons: ["Popular"],
          scoreBreakdown: {
            categoryScore: 4,
            textScore: 1,
            popularityScore: 3,
            freshnessScore: 1,
            ratingScore: 1,
            stockScore: 0,
            shopScore: 0,
            penaltyScore: 0,
          },
        },
      },
      {
        product: {
          id: "prod-2",
          name: "Moved Up Product",
          seoSlug: null,
          categoryName: "Jackets",
          brand: "North Berry",
          color: "Black",
          price: "1499",
          inStock: true,
          imageUrl: "https://example.com/image.jpg",
          shopName: "Ready Shop",
          shopSlug: "ready-shop",
        },
        rankMovement: null,
        ruleBasedV1: null,
        ruleBasedV2: {
          algorithm: "rule_based_v2",
          rank: 4,
          finalScore: 7,
          reasons: ["Popular"],
          scoreBreakdown: {
            categoryScore: 2,
            textScore: 0,
            popularityScore: 2,
            freshnessScore: 1,
            ratingScore: 1,
            stockScore: 0,
            shopScore: 1,
            penaltyScore: 0,
          },
        },
      },
    ],
  },
  candidateSnapshot: {
    scenarioType: "home",
    placement: "home",
    productId: null,
    query: null,
    limit: 5,
    generatedAt: "2026-06-06T13:30:00.000Z",
    comparedAlgorithms: ["rule_based_v1", "rule_based_v2"],
    items: [
      {
        product: {
          id: "prod-1",
          name: "Stable Product",
          seoSlug: null,
          categoryName: "Jackets",
          brand: "North Berry",
          color: "Black",
          price: "1499",
          inStock: true,
          imageUrl: "https://example.com/image.jpg",
          shopName: "Ready Shop",
          shopSlug: "ready-shop",
        },
        rankMovement: null,
        ruleBasedV1: null,
        ruleBasedV2: {
          algorithm: "rule_based_v2",
          rank: 1,
          finalScore: 11,
          reasons: ["Popular"],
          scoreBreakdown: {
            categoryScore: 4,
            textScore: 1,
            popularityScore: 3,
            freshnessScore: 1,
            ratingScore: 1,
            stockScore: 1,
            shopScore: 0,
            penaltyScore: 0,
          },
        },
      },
      {
        product: {
          id: "prod-2",
          name: "Moved Up Product",
          seoSlug: null,
          categoryName: "Jackets",
          brand: "North Berry",
          color: "Black",
          price: "1499",
          inStock: true,
          imageUrl: "https://example.com/image.jpg",
          shopName: "Ready Shop",
          shopSlug: "ready-shop",
        },
        rankMovement: null,
        ruleBasedV1: null,
        ruleBasedV2: {
          algorithm: "rule_based_v2",
          rank: 2,
          finalScore: 9,
          reasons: ["Popular", "Currently in stock"],
          scoreBreakdown: {
            categoryScore: 2,
            textScore: 0,
            popularityScore: 2,
            freshnessScore: 1,
            ratingScore: 1,
            stockScore: 1,
            shopScore: 1,
            penaltyScore: 0,
          },
        },
      },
    ],
  },
  expectedSummaryThresholds: {
    maxMovedDownCount: 2,
    maxRemovedCount: 1,
    maxScoreDelta: 5,
  },
};
