ALTER TABLE "product_images"
ADD COLUMN IF NOT EXISTS "storage_key" VARCHAR(1024),
ADD COLUMN IF NOT EXISTS "original_name" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "mime_type" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "size" INTEGER,
ADD COLUMN IF NOT EXISTS "image_type" VARCHAR(50) NOT NULL DEFAULT 'ORIGINAL',
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
