export const DELIVERY_PROVIDER = Symbol('DELIVERY_PROVIDER');
export const DELIVERY_AUTOMATED_CARRIERS = ['CDEK', 'YANDEX'] as const;
export const DELIVERY_CARRIERS = ['CDEK', 'YANDEX', 'MANUAL'] as const;
export const MANUAL_DELIVERY_STATUSES = [
  'NOT_CREATED',
  'CREATED_MANUALLY',
  'YANDEX_MANUAL_CREATED',
  'COURIER_ASSIGNED',
  'PICKED_UP',
  'ON_THE_WAY',
  'IN_TRANSIT',
  'DELIVERED',
  'CANCELLED',
  'FAILED',
] as const;
export const DELIVERY_TERMINAL_STATUSES = [
  'CANCELLED',
  'DELIVERED',
  'FAILED',
] as const;
export const DELIVERY_EXCEPTION_REASON_CODES = [
  'CUSTOMER_UNAVAILABLE',
  'WRONG_ADDRESS',
  'COURIER_CANCELLED',
  'SELLER_CANCELLED',
  'CUSTOMER_CANCELLED',
  'DAMAGED_PACKAGE',
  'LOST_PACKAGE',
  'DELIVERY_TIMEOUT',
  'OTHER',
] as const;
export const DELIVERY_COMMENT_VISIBILITIES = [
  'INTERNAL',
  'CUSTOMER_VISIBLE',
] as const;
export const DELIVERY_EXCEPTION_STATUSES = ['FAILED', 'CANCELLED'] as const;
