export const RETURN_REFUND_TYPES = [
  'REFUND_ONLY',
  'RETURN_AND_REFUND',
  'EXCHANGE_REQUEST',
  'PAYMENT_DISPUTE_ONLY',
] as const;

export const REFUND_REASONS = [
  'WRONG_SIZE',
  'ITEM_NOT_AS_DESCRIBED',
  'DAMAGED_ITEM',
  'MISSING_ITEM',
  'WRONG_ITEM',
  'LATE_DELIVERY',
  'BUYER_CHANGED_MIND',
  'PAYMENT_DISPUTE',
  'OTHER',
] as const;

export const RETURN_REFUND_STATUSES = [
  'OPENED',
  'WAITING_SELLER_RESPONSE',
  'SELLER_ACCEPTED',
  'SELLER_REJECTED',
  'WAITING_BUYER_EVIDENCE',
  'WAITING_RETURN_SHIPMENT',
  'RETURN_IN_TRANSIT',
  'RETURN_RECEIVED',
  'ADMIN_REVIEW',
  'APPROVED',
  'REJECTED',
  'REFUND_PENDING',
  'REFUND_MARKED_SENT',
  'REFUND_CONFIRMED',
  'CLOSED',
  'CANCELLED',
] as const;

export const RETURN_REFUND_MESSAGE_VISIBILITIES = [
  'PUBLIC',
  'INTERNAL_ADMIN',
] as const;

export const REFUND_TRANSFER_METHODS = [
  'SBP',
  'BANK_TRANSFER',
  'CASH',
  'OTHER',
] as const;

export const REFUND_TRANSFER_STATUSES = [
  'MARKED_SENT',
  'BUYER_CONFIRMED_RECEIVED',
  'ADMIN_CONFIRMED',
  'DISPUTED',
] as const;

export const SELLER_RETURN_ACTIONS = [
  'ACCEPT',
  'REJECT',
  'REQUEST_EVIDENCE',
  'ESCALATE_ADMIN',
] as const;

export const ADMIN_RETURN_DECISIONS = [
  'APPROVE',
  'REJECT',
  'REQUEST_MORE_EVIDENCE',
  'CLOSE',
  'OVERRIDE_REFUND_CONFIRMED',
] as const;

export const ACTIVE_RETURN_REFUND_STATUSES = RETURN_REFUND_STATUSES.filter(
  (status) => !['CLOSED', 'CANCELLED', 'REJECTED'].includes(status),
);

export const FINAL_PAYMENT_CONFIRMED_STATUSES = new Set([
  'PAID',
  'SELLER_CONFIRMED_DELIVERY_PAYMENT',
]);

export const RETURN_REFUND_SELLER_RESPONSE_SLA_DAYS = 3;
export const RETURN_REFUND_CUSTOMER_WINDOW_DAYS = 14;
